version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  vue-app:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
